trigger:
- master

steps:
- checkout: self

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    
# Cache task

- task: Cache@2
  inputs:
    key: 'pip | "$(Agent.OS)" | req.txt'
    restoreKeys: |
     pip | "$(Agent.OS)"
    path: $(PIP_CACHE_DIR)
  displayName: 'Cache pip packages'

# - script: |
#     python -m pip install --upgrade pip
#     pip install pandas requests openpyxl 
#   displayName: 'Install dependencies'


# - script: |
#    ls -al $(System.DefaultWorkingDirectory)
#   displayName: 'List directory content' 

  
# Pip install with cache
#   python -m pip install --find-links=$(PIP_CACHE_DIR) --no-index -r $(System.DefaultWorkingDirectory)/req.txt
   
- script: |
    python -m pip install --upgrade pip
    python -m pip install  -r $(System.DefaultWorkingDirectory)/req.txt
  displayName: 'Install dependencies'



- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: $(System.DefaultWorkingDirectory)/createOMP_Base.py

- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: $(System.DefaultWorkingDirectory)/addToOMP.py