name: Demo 4 - Release Actions

on:
  workflow_run:
    workflows: ["Demo5"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Empty Branch
        run: |
          git config --global user.name 'yashpal-paliwal'
          git config --global user.email 'yashpal.paliwal@jll.com'
          git checkout --orphan Release_Branch
          git reset --hard
          git clean -fdx

      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: buildArtifact
          path: build_output/

      - name: Create Zip File
        run: zip -r build_artifact.zip build_output/

      - name: Push Zip to Release Branch
        run: |
          git add build_artifact.zip
          git commit -m "Add build artifact zip"
          git push -f origin Release_Branch
