name: Demo 3 - Release Actions

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Step
        run: echo "Building the project..."

      - name: Create Build Artifact Directory
        run: |
          if [ ! -d "build_output" ]; then
            mkdir build_output
          fi
      - name: Create Build Artifact
        run: echo "This is a build artifact" > build_output/build_artifact.txt

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: buildArtifact
          path: build_output/

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: buildArtifact
          path: build_output/

      - name: Test Step
        run: echo "Running tests..."

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: buildArtifact
          path: build_output/

      - name: Deploy Step
        run: echo "Deploying the project..."

  release:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Empty Branch
        run: |
          git config --global user.name 'yashpal-paliwal'
          git config --global user.email 'yashpal.paliwal@jll.com'
          git checkout --orphan Release_Branch
          git reset --hard
          git clean -fdx

      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: buildArtifact
          path: build_output/

      - name: List Files in Build Output Directory
        run: ls -la build_output

      - name: Create Zip File
        run: |
          zip -r build_artifact.zip build_output/
      - name: List Files in Current Directory
        run: ls -la

      - name: Push Zip to Release Branch
        run: |
          git add build_artifact.zip
          git commit -m "Add build artifact zip"
          git push -f origin Release_Branch
