name: HTML Preview Workflow

on:
  workflow_dispatch:

jobs:
  html_preview_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: HTML Preview
        id: html_preview
        uses: pavi2410/html-preview-action@v2
        with:
          html_file: '/templates/index.html'

      
